# Import Library


In [1]:
import tensorflow as tf
import numpy as np

## 1. Random Tensor

In [3]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=4)
print(random_tensor.numpy())


[[ 0.29629603 -0.03141323 -0.05471061  0.03763179  2.564978  ]
 [-0.6494583  -0.6845234   0.43688074  1.4897977  -0.2399326 ]
 [ 0.04981674  0.41748443  0.11580934  0.8780719   0.27877015]
 [-1.5849335   1.1436394   1.0639356   1.1304685   1.3247743 ]
 [ 2.1117373  -0.863544   -1.8417858   0.4749224  -0.9902795 ]]


# 2. Prime Tensor


In [2]:
prime = [[2, 3, 5, 7, 11],[13, 17, 19, 23, 29],[31, 37, 41, 43, 47],[53, 59, 61, 71, 73],[79, 83, 89, 97, 1]]

In [4]:
prime_tensor = tf.convert_to_tensor(prime, dtype=tf.float32)
print(prime_tensor.numpy())

[[ 2.  3.  5.  7. 11.]
 [13. 17. 19. 23. 29.]
 [31. 37. 41. 43. 47.]
 [53. 59. 61. 71. 73.]
 [79. 83. 89. 97.  1.]]


# 3. Tensor Dimension


In [5]:
random_tensor.shape

TensorShape([5, 5])

In [6]:
prime_tensor.shape

TensorShape([5, 5])

# 4.Arithmetic Operations

***Addition***

In [7]:
print(tf.add(random_tensor, prime_tensor).numpy())

[[2.2962961e+00 2.9685867e+00 4.9452896e+00 7.0376320e+00 1.3564978e+01]
 [1.2350542e+01 1.6315477e+01 1.9436880e+01 2.4489798e+01 2.8760067e+01]
 [3.1049816e+01 3.7417484e+01 4.1115810e+01 4.3878071e+01 4.7278770e+01]
 [5.1415066e+01 6.0143639e+01 6.2063934e+01 7.2130470e+01 7.4324776e+01]
 [8.1111740e+01 8.2136459e+01 8.7158211e+01 9.7474922e+01 9.7205043e-03]]



**Multiplication**

In [8]:
print(tf.multiply(random_tensor, prime_tensor).numpy())

[[ 5.9259206e-01 -9.4239704e-02 -2.7355304e-01  2.6342255e-01
   2.8214756e+01]
 [-8.4429579e+00 -1.1636898e+01  8.3007336e+00  3.4265347e+01
  -6.9580455e+00]
 [ 1.5443188e+00  1.5446924e+01  4.7481828e+00  3.7757092e+01
   1.3102197e+01]
 [-8.4001480e+01  6.7474724e+01  6.4900070e+01  8.0263260e+01
   9.6708519e+01]
 [ 1.6682724e+02 -7.1674149e+01 -1.6391893e+02  4.6067471e+01
  -9.9027950e-01]]


**Substraction**

In [10]:
print(tf.subtract(random_tensor, prime_tensor).numpy())

[[ -1.703704   -3.0314133  -5.0547104  -6.962368   -8.435022 ]
 [-13.649458  -17.684523  -18.56312   -21.510202  -29.239933 ]
 [-30.950184  -36.582516  -40.88419   -42.12193   -46.72123  ]
 [-54.584934  -57.85636   -59.936066  -69.86953   -71.675224 ]
 [-76.88826   -83.86354   -90.84179   -96.52508    -1.9902794]]


**Divide**

In [11]:
print(tf.divide(random_tensor, prime_tensor).numpy())

[[ 0.14814802 -0.01047108 -0.01094212  0.00537597  0.23317981]
 [-0.04995833 -0.04026608  0.02299372  0.06477381 -0.00827354]
 [ 0.00160699  0.01128336  0.00282462  0.02042028  0.00593128]
 [-0.02990441  0.01938372  0.01744157  0.01592209  0.01814759]
 [ 0.02673085 -0.01040414 -0.02069422  0.00489611 -0.9902795 ]]


**Power**

In [12]:
print(tf.pow(random_tensor, prime_tensor).numpy())

[[ 8.7791339e-02 -3.0998308e-05 -4.9018240e-07  1.0687699e-10
   3.1616943e+04]
 [-3.6573492e-03 -1.5907470e-03  1.4685713e-07  9.5924150e+03
  -1.0533880e-18]
 [ 0.0000000e+00  9.1979401e-15  0.0000000e+00  3.7307271e-03
   8.4445118e-27]
 [-3.9864439e+10  2.7482639e+03  4.3836586e+01  6.0443652e+03
   8.2481670e+08]
 [ 4.4314982e+25 -5.1476682e-06 -4.0390710e+23  4.2893989e-32
  -9.9027950e-01]]


# 5. Max and Min


In [15]:
print(f'Nilai Minimum Random : {tf.reduce_max(random_tensor).numpy()}')
print(f'Nilai Maksimum Random : {tf.reduce_min(random_tensor).numpy()}')

Nilai Minimum Random : 2.5649778842926025
Nilai Maksimum Random : -1.8417857885360718


# 6. Concatenation

In [16]:
print(tf.concat([random_tensor, prime_tensor], axis=0).numpy())

[[ 2.9629603e-01 -3.1413235e-02 -5.4710608e-02  3.7631791e-02
   2.5649779e+00]
 [-6.4945829e-01 -6.8452340e-01  4.3688074e-01  1.4897977e+00
  -2.3993260e-01]
 [ 4.9816735e-02  4.1748443e-01  1.1580934e-01  8.7807190e-01
   2.7877015e-01]
 [-1.5849335e+00  1.1436394e+00  1.0639356e+00  1.1304685e+00
   1.3247743e+00]
 [ 2.1117373e+00 -8.6354399e-01 -1.8417858e+00  4.7492239e-01
  -9.9027950e-01]
 [ 2.0000000e+00  3.0000000e+00  5.0000000e+00  7.0000000e+00
   1.1000000e+01]
 [ 1.3000000e+01  1.7000000e+01  1.9000000e+01  2.3000000e+01
   2.9000000e+01]
 [ 3.1000000e+01  3.7000000e+01  4.1000000e+01  4.3000000e+01
   4.7000000e+01]
 [ 5.3000000e+01  5.9000000e+01  6.1000000e+01  7.1000000e+01
   7.3000000e+01]
 [ 7.9000000e+01  8.3000000e+01  8.9000000e+01  9.7000000e+01
   1.0000000e+00]]


In [17]:
print(tf.concat([random_tensor, prime_tensor], axis=1).numpy())

[[ 2.9629603e-01 -3.1413235e-02 -5.4710608e-02  3.7631791e-02
   2.5649779e+00  2.0000000e+00  3.0000000e+00  5.0000000e+00
   7.0000000e+00  1.1000000e+01]
 [-6.4945829e-01 -6.8452340e-01  4.3688074e-01  1.4897977e+00
  -2.3993260e-01  1.3000000e+01  1.7000000e+01  1.9000000e+01
   2.3000000e+01  2.9000000e+01]
 [ 4.9816735e-02  4.1748443e-01  1.1580934e-01  8.7807190e-01
   2.7877015e-01  3.1000000e+01  3.7000000e+01  4.1000000e+01
   4.3000000e+01  4.7000000e+01]
 [-1.5849335e+00  1.1436394e+00  1.0639356e+00  1.1304685e+00
   1.3247743e+00  5.3000000e+01  5.9000000e+01  6.1000000e+01
   7.1000000e+01  7.3000000e+01]
 [ 2.1117373e+00 -8.6354399e-01 -1.8417858e+00  4.7492239e-01
  -9.9027950e-01  7.9000000e+01  8.3000000e+01  8.9000000e+01
   9.7000000e+01  1.0000000e+00]]


# 7. Sorting

In [18]:
print(tf.sort(random_tensor, direction='DESCENDING', axis=0).numpy())

[[ 2.1117373   1.1436394   1.0639356   1.4897977   2.564978  ]
 [ 0.29629603  0.41748443  0.43688074  1.1304685   1.3247743 ]
 [ 0.04981674 -0.03141323  0.11580934  0.8780719   0.27877015]
 [-0.6494583  -0.6845234  -0.05471061  0.4749224  -0.2399326 ]
 [-1.5849335  -0.863544   -1.8417858   0.03763179 -0.9902795 ]]
